#!/bin/bash
url='http://localhost:8080'

echo "# $*"

case $1 in
    session)
        rm -f cookies.txt
        curl -v -c cookies.txt -b cookies.txt -X GET "$url/todo/"
        ;;
    signup)
        curl -v -c cookies.txt -b cookies.txt -X POST "$url/todo/signup/" \
            -d "username=$2&password1=$3&password2=$3"
        ;;
    login)
        curl -v -c cookies.txt -b cookies.txt -X POST "$url/todo/login/" \
            -d "username=$2&password=$3"
        ;;
    
    get-tasks)
        curl -v -c cookies.txt -b cookies.txt -X GET "$url/todo/tasks/"
        ;;

    create-task)
        curl -v -c cookies.txt -b cookies.txt -X POST "$url/todo/tasks/" \
            -d "description=$2"
        ;;

    get-task)
        curl -v -c cookies.txt -b cookies.txt -X GET "$url/todo/tasks/$2"
        ;;

    update-task)
        curl -v -c cookies.txt -b cookies.txt -X PUT "$url/todo/tasks/$2" \
            -d "is_done=$3&description=$4"
        ;;

    delete-task)
        curl -v -c cookies.txt -b cookies.txt -X DELETE "$url/todo/tasks/$2"
        ;;

    go-all-out)
        rm cookies.txt
        $0 session
        $0 signup "joost" "foo"
        $0 login "joost" "foo"
        $0 get-tasks
        $0 create-task "whatever"
        $0 get-tasks
        $0 update-task 1 "true" "whatever"
        $0 get-tasks
        $0 delete-task 1
esac

echo
